(global-unset-key "\M-g")
(global-set-key "\M-g" 'goto-line)
(global-set-key "\r" 'newline-and-indent)
(global-set-key "\C-xn" 'my-next-window)
(global-set-key "\C-xp" 'my-previous-window)
(define-key minibuffer-local-completion-map '[tab] 'minibuffer-complete)
(define-key minibuffer-local-completion-map '[spc] 'minibuffer-complete-word)
(define-key minibuffer-local-must-match-map '[tab] 'minibuffer-complete)
(define-key minibuffer-local-must-match-map '[spc] 'minibuffer-complete-word)
(global-set-key "\C-ct" 'transpose-lines)
(global-set-key "\C-\M-l" 'my-other-buffer)
(global-unset-key "\C-\\")
(global-set-key "\C-\\" 'compile)
(global-set-key "\C-x\C-b" 'ibuffer)
;; (global-set-key "\C-xb" 'iswitchb-buffer)
(global-set-key [C-M-left] 'previous-buffer)
(global-set-key [C-M-right] 'next-buffer)

(global-set-key [?\C-.] 'tags-search)
(global-set-key [?\C-,] 'tags-loop-continue)

(define-key ctl-x-4-map "k" 'other-window-send-keys)

(eval-after-load 'outline
  '(progn
     (define-key outline-minor-mode-map "\C-c[" 'show-entry)
     (define-key outline-minor-mode-map "\C-c]" 'hide-entry)
     (define-key outline-minor-mode-map "\C-c{" 'show-all)
     (define-key outline-minor-mode-map "\C-c}" 'hide-body)))

;;;;;;;;;;;;;;;; ctrl-z keymap ;;;;;;;;;;;;;;;;

(defun ctl-z-help ()
  (interactive)
  (message "Welcome to Ctl-z"))

(defvar ctl-z-map (make-sparse-keymap))

(global-unset-key "\C-z")
(define-prefix-command 'ctl-z-prefix 'ctl-z-map "Ctl-Z")
(define-key global-map "\C-z" 'ctl-z-prefix)

(define-key ctl-z-map "." 'find-tag)
(define-key ctl-z-map "2" '2col-view)
(define-key ctl-z-map "3" '3col-view)
(define-key ctl-z-map "9" 'fill-vertical-panes)
(define-key ctl-z-map "<" 'pop-tag-mark)
(define-key ctl-z-map "\C-b" 'winner-undo)
(define-key ctl-z-map "\C-f" 'winner-redo)
(define-key ctl-z-map "\C-l" 'bury-buffer)
(define-key ctl-z-map "g" 'toggle-debug-on-error)
(define-key ctl-z-map "j" 'jump-to-register)
(define-key ctl-z-map "l" 'cider-jack-in)
(define-key ctl-z-map "o" 'browse-url-chromium)
(define-key ctl-z-map "r" 'cider-switch-to-current-repl-buffer)
(define-key ctl-z-map "t" 'toggle-truncate-lines)
(define-key ctl-z-map "u" 'browse-url)
(define-key ctl-z-map "v" 'magit-status)
(define-key ctl-z-map "w" 'window-configuration-to-register)
(define-key ctl-z-map "W" 'visual-line-mode)
(define-key ctl-z-map "|" 'toggle-window-split)
(define-key ctl-z-map [left]  'buf-move-left)
(define-key ctl-z-map [right] 'buf-move-right)
(define-key ctl-z-map [down]  'buf-move-down)
(define-key ctl-z-map [up]    'buf-move-up)
(define-key ctl-z-map "p" 'emms-pause)

(define-key dired-mode-map [C-return] 'dired-open-file)
